---
kind: pipeline
name: default
type: kubernetes
services:
  - name: selenium
    image: selenium/standalone-chrome:3.141.0
    environment:
      START_XVFB: "FALSE"
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    environment:
      DOCKER_TLS_CERTDIR: ""
steps:
  - name: install
    image: quay.io/ukhomeofficedigital/asl-base:v12
    commands:
      - npm ci
  - name: lint
    image: quay.io/ukhomeofficedigital/asl-base:v12
    commands:
      - npm run test:lint
    depends_on:
      - install
  - name: ppl
    image: quay.io/ukhomeofficedigital/asl-base:v12
    environment:
      KEYCLOAK_PASSWORD:
        from_secret: keycloak_password
    commands:
      - npm test -- ppl --env dev --fast
    depends_on:
      - lint
  - name: legacy ppl
    image: quay.io/ukhomeofficedigital/asl-base:v12
    environment:
      KEYCLOAK_PASSWORD:
        from_secret: keycloak_password
    commands:
      - npm test -- ppl --env dev --fast --legacy
    depends_on:
      - lint
  - name: place
    image: quay.io/ukhomeofficedigital/asl-base:v12
    environment:
      KEYCLOAK_PASSWORD:
        from_secret: keycloak_password
    commands:
      - npm test -- place --env dev
    depends_on:
      - lint
  - name: pil
    image: quay.io/ukhomeofficedigital/asl-base:v12
    environment:
      KEYCLOAK_PASSWORD:
        from_secret: keycloak_password
    commands:
      - npm test -- pil --env dev
    depends_on:
      - lint
  - name: docker build
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - docker build -t asl-autoproject .
    depends_on:
      - ppl
      - legacy ppl
      - place
      - pil
  - name: docker push
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag asl-autoproject quay.io/ukhomeofficedigital/asl-autoproject:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/asl-autoproject:$${DRONE_COMMIT_SHA}
      - docker tag asl-autoproject quay.io/ukhomeofficedigital/asl-autoproject:latest
      - docker push quay.io/ukhomeofficedigital/asl-autoproject:latest
    when:
      branch: master
    depends_on:
      - docker build
trigger:
  event: push