#! /bin/bash
export PUB_PROD="https://public-ui.prod.asl.homeoffice.gov.uk/"
export INT_PROC="https://internal-ui.prod.asl.homeoffice.gov.uk/"
export PUB_DEV='https://public-ui.dev.asl.homeoffice.gov.uk/'
export INT_DEV='https://internal-ui.dev.asl.homeoffice.gov.uk/'
export PUB_PRE='https://public-ui.preprod.asl.homeoffice.gov.uk/'
export INT_PRE='https://internal-ui.preprod.asl.homeoffice.gov.uk/'
export DT_DEV='https://ppl-staging.herokuapp.com/'
export DT_PROD='https://ppl-prototype.herokuapp.com/'

[ -z ${TPW} ] && echo "No password set.' " && exit 1;
if [ "${1}" = "pub" ]; then
   URL=${PUB_PRE}
elif [ "${1}" = "ppl" ]; then
   URL=${DT_PROD}
else
   URL=${PUB_DEV}
fi

./test_li.pl ${2} ${TPW} ${URL} text.txt ${3}

