#! /bin/bash
##export TPW=${1}
export TEST_START="TEST${RANDOM}"
export PUB_PROD="https://public-ui.prod.asl.homeoffice.gov.uk/"
export INT_PROC="https://internal-ui.prod.asl.homeoffice.gov.uk/"
export PUB_DEV='https://public-ui.dev.asl.homeoffice.gov.uk/'
export INT_DEV='https://internal-ui.dev.asl.homeoffice.gov.uk/'
export PUB_PRE='https://public-ui.preprod.asl.homeoffice.gov.uk/'
export INT_PRE='https://internal-ui.preprod.asl.homeoffice.gov.uk/'
export DT_DEV='https://ppl-staging.herokuapp.com/'
export DT_PROD='https://ppl-prototype.herokuapp.com/'

echo "The password is $TPW"
echo "PPL application starts ${TEST_START}"
./run_li ${2} holc ${TEST_START}
./run_rl ${2} inspector ${TEST_START}
./run_gl ${2} licensing ${TEST_START}

