#! /bin/bash
pkill chrome
[ -z ${TPW} ] && echo "No password set." && exit 1;
echo "Recommend licence test"
if [ "${1}" = "pub" ]; then
   URL=${INT_PRE}
else
   URL=${INT_DEV}
fi

./test_rl.pl ${2} ${TPW}  ${URL} text.txt ${3}

